# Generated by Django 5.0.4 on 2024-04-16 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'taxis',
            },
        ),
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('taxi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet_management.taxi')),
            ],
            options={
                'db_table': 'trajectories',
            },
        ),
    ]
