# Generated by Django 5.0.4 on 2024-04-15 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='taxi',
            table='taxis',
        ),
    ]
